
import Head from 'next/head'
import Navbar from '../Navbar'
import styles from './MainLayout.module.css'
import React, { ReactNode } from 'react';

interface MainLayoutProps {
  children: ReactNode;
  title?: string;
}




const MainLayout: React.FC<MainLayoutProps> = ({children, title}) => {
  return (
    <>
      <Head>
        <title>{title}</title>

        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
      <Navbar />
      </main>
      { children }
    </>
  )
}

export default MainLayout
